language: haskell
ghc:
  - 7.4
  - 7.6
  - 7.8

install:
  - cabal update
  - echo $PATH
  - which cabal
  - cabal install -j --only-dependencies --enable-tests

script:
  - touch ChangeLog # Create ChangeLog if we're not on the release branch
  - cabal check
  - if [ -n "$(ghc --version | awk '{ print $8 }' | sed -n '/^7.8/p')" ]; then export WERROR="--ghc-option=-Werror"; fi
  - cabal configure --enable-tests $WERROR
  - cabal build
#  - cabal test
